'use client';

import * as React from 'react';
import Link from 'next/link';
import { useAdminOverview, type AdminUser, type AdminOverview } from './admin-overview-provider';

type Created = { username: string; email: string; password: string };

function Icon({ children }: { children: React.ReactNode }) { return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" className="size-5" aria-hidden="true">{children}</svg>; }
function date(value: string | null) { return value ? new Intl.DateTimeFormat('he-IL', { dateStyle: 'medium' }).format(new Date(value)) : 'אין פעילות עדיין'; }

export default function AdminPage() {
  const { overview, setOverview, loading, refresh } = useAdminOverview();
  const [created, setCreated] = React.useState<Created | null>(null);
  const [error, setError] = React.useState('');
  const [query, setQuery] = React.useState('');
  const [busy, setBusy] = React.useState(false);
  const [copied, setCopied] = React.useState(false);
  const users = overview.users.filter((u) => `${u.username} ${u.email}`.toLowerCase().includes(query.toLowerCase()));
  async function create(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(''); setCreated(null); const email = new FormData(event.currentTarget).get('email'); try { const r = await fetch('/api/admin/users', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ email }) }); const d = await r.json(); if (!r.ok) throw new Error(d.error || 'לא ניתן ליצור משתמש'); setCreated(d.user); event.currentTarget.reset(); await refresh(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  async function reset(username: string) { setBusy(true); setError(''); setCreated(null); try { const r = await fetch('/api/admin/users', { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ username }) }); const d = await r.json(); if (!r.ok) throw new Error(d.error || 'לא ניתן לאפס סיסמה'); setCreated(d.user); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  async function remove(username: string) { if (!window.confirm(`למחוק את ${username}? גם נתוני הבטא וחיבורי WhatsApp שלו יימחקו.`)) return; setBusy(true); setError(''); try { const r = await fetch('/api/admin/users', { method: 'DELETE', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ username }) }); const d = await r.json(); if (!r.ok) throw new Error(d.error || 'לא ניתן למחוק משתמש'); await refresh(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  async function copy() { if (!created) return; await navigator.clipboard.writeText(`שם משתמש: ${created.username}\nסיסמה זמנית: ${created.password}\nכניסה: ${location.origin}/login`); setCopied(true); setTimeout(() => setCopied(false), 1800); }
  const cards = [
    ['זוגות רשומים', overview.metrics.registeredUsers, `מתוך ${overview.betaCapacity} מקומות`],
    ['מקומות פנויים', overview.metrics.availableSeats, 'אפשר לצרף זוגות חדשים'],
    ['מרחבים פעילים', overview.metrics.activeWorkspaces, 'עם נתונים מבודדים'],
    ['שליחות שתועדו', overview.metrics.totalSendJobs, `${overview.metrics.totalGuests} מוזמנים בכל הבטא`],
  ];
  return <main className="min-h-dvh bg-[#101827] px-4 py-5 text-slate-100 sm:px-6 lg:px-8" dir="rtl"><div className="mx-auto max-w-7xl">
    <header className="mb-7 flex flex-col gap-5 border-b border-white/10 pb-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="flex items-center gap-2 text-xs font-bold tracking-[.18em] text-sky-300"><span className="size-2 rounded-full bg-emerald-400 shadow-[0_0_12px_#34d399]" />BETA CONTROL ROOM</p><h1 className="mt-2 text-3xl font-bold sm:text-4xl">ניהול הבטא</h1><p className="mt-2 max-w-xl text-sm leading-6 text-slate-400">ניהול גישה, מדדי שימוש ותפעול בטוח — בלי לחשוף תוכן הודעות או פרטי אימות.</p></div><div className="flex flex-wrap gap-2"><button onClick={() => void refresh().catch((error: Error) => setError(error.message))} disabled={loading} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-white/15 bg-white/5 px-4 text-sm font-bold transition hover:bg-white/10 disabled:opacity-50 focus-visible:outline-2 focus-visible:outline-sky-300"><Icon><path d="M20 11a8 8 0 0 0-15-2M4 5v4h4M4 13a8 8 0 0 0 15 2M20 19v-4h-4" /></Icon>רענון</button><Link href="/account/password" className="inline-flex min-h-11 items-center rounded-xl border border-white/15 bg-white/5 px-4 text-sm font-bold transition hover:bg-white/10">סיסמת אדמין</Link><Link href="/" className="inline-flex min-h-11 items-center rounded-xl bg-sky-400 px-4 text-sm font-extrabold text-slate-950 transition hover:bg-sky-300">למערכת הזוגות</Link></div></header>
    <section aria-label="מדדי בטא" className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{cards.map(([label, value, detail]) => <article key={label} className="rounded-2xl border border-white/10 bg-white/[.045] p-5 shadow-[0_14px_40px_rgba(2,6,23,.18)]"><div className="mb-5 flex justify-between"><span className="grid size-10 place-items-center rounded-xl bg-sky-400/10 text-sky-300"><Icon><circle cx="12" cy="12" r="8" /><path d="M12 8v4l3 2" /></Icon></span><span className="size-2 rounded-full bg-emerald-400" /></div><p className="text-3xl font-bold tabular-nums">{value}</p><p className="mt-1 text-sm font-semibold">{label}</p><p className="mt-1 text-xs text-slate-500">{detail}</p></article>)}</section>
    <section className="mt-6 grid gap-6 lg:grid-cols-[1.6fr_.9fr]"><div className="rounded-2xl border border-white/10 bg-slate-900/60 p-5 sm:p-6"><p className="text-xs font-bold tracking-[.16em] text-sky-300">ACCESS</p><h2 className="mt-1 text-xl font-bold">צירוף זוג חדש</h2><p className="mt-1 text-sm text-slate-400">נוצר מרחב עבודה מבודד ופרטי גישה חד־פעמיים.</p><form onSubmit={create} className="mt-6 flex flex-col gap-3 sm:flex-row"><label className="sr-only" htmlFor="email">אימייל הזוג</label><input id="email" required name="email" type="email" placeholder="couple@example.com" className="min-h-12 min-w-0 flex-1 rounded-xl border border-white/12 bg-slate-950/60 px-4 text-base outline-none placeholder:text-slate-600 focus:border-sky-300 focus:ring-2 focus:ring-sky-300/25"/><button disabled={busy} className="min-h-12 rounded-xl bg-emerald-400 px-5 text-sm font-extrabold text-slate-950 transition hover:bg-emerald-300 disabled:opacity-50">{busy ? 'שומר…' : 'יצירת גישה'}</button></form>{error && <p role="alert" className="mt-4 rounded-xl border border-rose-400/25 bg-rose-400/10 px-4 py-3 text-sm text-rose-200">{error}</p>}{created && <section aria-live="polite" className="mt-5 rounded-2xl border border-emerald-300/25 bg-emerald-300/[.08] p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-bold text-emerald-200">פרטי הגישה מוכנים</p><p className="text-xs text-slate-400">הסיסמה מוצגת כעת בלבד — מסרו אותה בערוץ פרטי.</p></div><button onClick={() => void copy()} className="min-h-10 rounded-lg border border-emerald-200/25 px-3 text-xs font-bold text-emerald-100">{copied ? 'הועתק' : 'העתקת פרטים'}</button></div><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-3"><div><dt className="text-xs text-slate-500">אימייל</dt><dd dir="ltr" className="break-all font-mono">{created.email}</dd></div><div><dt className="text-xs text-slate-500">שם משתמש</dt><dd dir="ltr" className="font-mono font-bold">{created.username}</dd></div><div><dt className="text-xs text-slate-500">סיסמה זמנית</dt><dd dir="ltr" className="font-mono font-bold">{created.password}</dd></div></dl></section>}</div>
      <aside className="rounded-2xl border border-sky-300/15 bg-gradient-to-b from-sky-400/[.09] to-white/[.035] p-5"><p className="text-xs font-bold tracking-[.16em] text-sky-300">OPERATIONS</p><h2 className="mt-1 text-xl font-bold">שגרת בטא בריאה</h2><ol className="mt-5 space-y-4 text-sm"><li className="flex gap-3"><b className="grid size-6 shrink-0 place-items-center rounded-full bg-sky-300/15 text-sky-200">1</b><span><strong className="block">לפני צירוף</strong><span className="text-slate-400">הזוג מבין שזו בטא ושומר עותק מקומי.</span></span></li><li className="flex gap-3"><b className="grid size-6 shrink-0 place-items-center rounded-full bg-sky-300/15 text-sky-200">2</b><span><strong className="block">לפני שליחה</strong><span className="text-slate-400">שולחים הודעת ניסיון למספר שבבעלותם.</span></span></li><li className="flex gap-3"><b className="grid size-6 shrink-0 place-items-center rounded-full bg-sky-300/15 text-sky-200">3</b><span><strong className="block">אחרי שימוש</strong><span className="text-slate-400">אוספים משוב קצר ומתעדים תקלה.</span></span></li></ol><a href="/api/workspace/backup" className="mt-6 flex min-h-11 items-center justify-center rounded-xl border border-white/12 bg-white/5 text-sm font-bold transition hover:bg-white/10">גיבוי מרחב האדמין</a></aside></section>
    <section className="mt-6 overflow-hidden rounded-2xl border border-white/10 bg-slate-900/60"><div className="flex flex-col gap-4 border-b border-white/10 px-5 py-5 sm:flex-row sm:items-center sm:justify-between sm:px-6"><div><p className="text-xs font-bold tracking-[.16em] text-sky-300">BETA DIRECTORY</p><h2 className="mt-1 text-xl font-bold">הזוגות בבטא</h2></div><label className="sm:w-72"><span className="sr-only">חיפוש זוג</span><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="חיפוש שם משתמש או אימייל" className="min-h-11 w-full rounded-xl border border-white/12 bg-slate-950/60 px-4 text-sm outline-none placeholder:text-slate-600 focus:border-sky-300"/></label></div>{users.length ? <div className="overflow-x-auto"><table className="min-w-[780px] w-full text-right text-sm"><thead className="bg-white/[.025] text-xs text-slate-500"><tr><th className="px-6 py-4">זוג / גישה</th><th>מרחב</th><th>פעילות</th><th>הצטרפות</th><th className="px-6 text-left">פעולות</th></tr></thead><tbody className="divide-y divide-white/8">{users.map(user => <tr key={user.username} className="transition hover:bg-white/[.025]"><td className="px-6 py-4"><p dir="ltr" className="font-mono font-bold">{user.username}</p><p dir="ltr" className="mt-1 text-xs text-slate-500">{user.email}</p></td><td><span className={user.hasWorkspace ? 'text-emerald-300' : 'text-slate-500'}>{user.hasWorkspace ? '● מבודד ומוכן' : '○ טרם הופעל'}</span></td><td><p className="font-bold tabular-nums">{user.guests} מוזמנים · {user.sends} שליחות</p><p className="text-xs text-slate-500">{date(user.lastActivityAt)}</p></td><td className="text-slate-400">{date(user.createdAt)}</td><td className="px-6"><div className="flex justify-end gap-2"><button disabled={busy} onClick={() => void reset(user.username)} className="min-h-10 rounded-lg border border-sky-300/20 px-3 text-xs font-bold text-sky-200 disabled:opacity-50">איפוס סיסמה</button><button disabled={busy} onClick={() => void remove(user.username)} className="min-h-10 rounded-lg border border-rose-300/20 px-3 text-xs font-bold text-rose-200 disabled:opacity-50">מחיקה</button></div></td></tr>)}</tbody></table></div> : <div className="px-6 py-14 text-center"><p className="font-bold">לא נמצאו זוגות</p><p className="mt-1 text-sm text-slate-500">אפשר לשנות חיפוש או לצרף זוג ראשון לבטא.</p></div>}</section>
  </div></main>;
}
